mail_address: camille.roux@univ-lille.fr
infile: /home/croux/Documents/ABConline/reduced_fastaFile.fasta
region: coding
nspecies: 2
nameA: txn
nameB: ama
nameOutgroup: NA
config_yaml: /home/croux/Programmes/DILS/bin/example_config_2pop.yaml 
timeStamp: variableBeta3roundsV3
population_growth: variable
modeBarrier: beta 
max_N_tolerated: 0.05
Lmin: 100
nMin: 10
mu: 0.000000003
rho_over_theta: 1
N_min: 0
N_max: 40000000
Tsplit_min: 0
Tsplit_max: 20000000
M_min: 0.4
M_max: 50
